### ISSUE TITLE
How can I validate recurring payment?

### ISSUE THREAD

**Issue by takielias** [sharik709/laravel-authorizenet#2]
How can I make & validate recurring payments?

**Comment by sharik709** [comment]
Hello @takielias I'm working on adding feature for recurring payment. It should be up before next week. Ill post here and add step by step detail on how to make and validate your recurring payment and related functionalities. Thank you.

**Comment by sharik709** [comment]
@takielias I've added subscription or recurring payment functionalities please read readme to understand how to use it. Thank you :)

**Comment by takielias** [comment]
@sharik709  No doubt this is a great package for laravel developer. It would be super helpful if you add subscription status checking feature. It's required to verify subscription status according to multiple transactions process.

**Comment by sharik709** [comment]
Yeah it's there. I think I forgot to add it into the readme. Ill check and get back

**Comment by sharik709** [comment]
here is how you check the subscription status `$response = $user->anet()->subs()->getStatus($subscriptionId);`
