### ISSUE TITLE
Sandbox auth returns invalid

### ISSUE THREAD

**Issue by khrelian** [sharik709/laravel-authorizenet#4]
Hi Sharik, I'm trying to use your plugin to a new e-commerce site I'm currently working on. I've set the .env with required vars on your readme file (AUTHORIZE_NET_LOGIN_ID, AUTHORIZE_NET_CLIENT_KEY, AUTHORIZE_NET_TRANSACTION_KEY). However, when I try creating a new customer profile using $user->anet()->createCustomerProfile(), it always returns "User authentication failed due to invalid authentication values" when the credentials I put were correct. I should also say that I'm using the sandbox version. I hope you could help me on this.

**Comment by sharik709** [comment]
Hello @khrelian,

Can you please check in `php artisan tinker` if you are getting correct values for following config keys
`config('authorizenet.transaction_key')` and `config('authorizenet.login_id')`

Thanks :)

**Comment by khrelian** [comment]
Sorry, turns out I just had to regenerate a new transaction key. :D

**Comment by khrelian** [comment]
Thanks for making this available. Stay awesome!

**Comment by sharik709** [comment]
lol. Please feel free to create an issue here. In case, if you still have any issues.

**Comment by khrelian** [comment]
will do. Thanks! hahaha

**Comment by musikel** [comment]
hi @sharik709 , thanks for this library. 

may I know how can I get authorize.net client key? 

thanks!
